In [1]:
import pickle
import numpy as np
features_list=np.array(pickle.load(open('embedding.pkl','rb')))
file_names=pickle.load(open('filenames.pkl','rb'))
import tensorflow
from tensorflow.keras.preprocessing import image
from tensorflow.keras.layers import GlobalMaxPooling2D
from tensorflow.keras.applications.resnet50 import ResNet50,preprocess_input
from numpy.linalg import norm
import numpy as np
import matplotlib as plt

In [2]:
model=ResNet50(weights="imagenet",include_top=False,input_shape=(224,224,3))
model.trainable=False
model=tensorflow.keras.Sequential([model,GlobalMaxPooling2D()])

In [3]:
img=image.load_img("C:\\Users\\hp\\Downloads\\images\\1540.jpg",target_size=(224,224))
img_arr=image.img_to_array(img)
expand_img_arr= np.expand_dims(img_arr,axis=0)
preprocessed_img=preprocess_input(expand_img_arr)
result=model.predict(preprocessed_img).flatten()
normalized_result=result/norm(result)
    
print(normalized_result)

[0.00940838 0.05376235 0.0058136  ... 0.01908367 0.03705109 0.01656622]


In [4]:
features_list

array([[0.        , 0.01761616, 0.00171594, ..., 0.01247232, 0.02726384,
        0.06899207],
       [0.        , 0.03648943, 0.        , ..., 0.00997928, 0.02375534,
        0.04649908],
       [0.        , 0.03507707, 0.00732284, ..., 0.00283519, 0.        ,
        0.05435891],
       ...,
       [0.        , 0.05594851, 0.00553631, ..., 0.00670328, 0.01752765,
        0.00746652],
       [0.        , 0.02520914, 0.00274131, ..., 0.00833132, 0.01841293,
        0.0042276 ],
       [0.        , 0.03215053, 0.00704543, ..., 0.00988327, 0.02218141,
        0.00713839]], dtype=float32)

In [5]:

from sklearn.neighbors import NearestNeighbors
neigh = NearestNeighbors(n_neighbors=5,algorithm='brute',metric='euclidean')
neigh.fit(features_list)

NearestNeighbors(algorithm='brute', metric='euclidean')

In [6]:
distance,indices=neigh.kneighbors([normalized_result])

In [7]:
indices[0]

array([ 4557,  4522,  8889,  9088, 10378], dtype=int64)

In [8]:
import cv2
for file in indices[0][1:6]:
    temp_img=cv2.imread(file_names[file])
    cv2.imshow('output',temp_img)
    cv2.waitKey(0)

In [9]:
indices[0][0]

4557